- README.rst
- docs/intro.rst
- src/openfermion/ops/_interaction_tensor_test.py
- src/openfermion/utils/__init__.py
- src/openfermion/utils/_jellium_hf_state.py
- src/openfermion/utils/_jellium_hf_state_test.py
Changed code in _jw_hf_state.py to use dok_matrix instead of csr_matrix in order to avoid sparse efficiency warning.
> fixed sparse efficiency warning

- src/openfermion/utils/_operator_utils.py
For instance, I wanted to give this function numpy arrays.
> Allowed more general types to be accepted by commutator function.

- src/openfermion/utils/__init__.py
- src/openfermion/utils/_unitary_cc.py
- src/openfermion/utils/_unitary_cc_test.py
Moves the routines related to UCC that were independent of ProjectQ out of the OpenFermion-ProjectQ repo back into the main branch under utilities.  Merge this before merging branch.
> Move UCC independent functions back in OpenFermion

- src/openfermion/hamiltonians/__init__.py
- src/openfermion/hamiltonians/_hubbard.py
- src/openfermion/hamiltonians/_hubbard_test.py
I added an alternative version of the routine for creating the Fermi Hubbard hamiltonian. In this version the repulsion term U n_{i,\uparrow} n_{i,\downarrow} is replaced by  U (n_{i,\uparrow}-1/2) (n_{i,\downarrow}-1/2), which is unchanged by a particle-hole transformation. This version has the advantage that at chemical potential and magnetic field equal zero, the ground state is always the one at half-filling and the energy is symmetric with respect to chemical potential = 0. This is more convenient for benchmarks than the previous version. Look at the energies for a 2x2 lattice:
For now it is a separate routine.
> Added hubbard model with particle-hole symmetry

- src/openfermion/utils/_slater_determinants.py
- src/openfermion/utils/_slater_determinants_test.py
The main things I changed were:
- The canonical form for antisymmetric matrices should have nonnegative entries in the upper right block; I forgot to do this initially.
- Particle-hole transformations used in the preparation of fermionic Gaussian states are now on the last site, rather than the first. The particle-hole transformation on the last site is easier to implement on an actual device.
> Fixes for Slater determinant preparation

- src/openfermion/ops/_quadratic_hamiltonian.py
- src/openfermion/ops/_quadratic_hamiltonian_test.py
- src/openfermion/utils/__init__.py
- src/openfermion/utils/_slater_determinants.py
- src/openfermion/utils/_slater_determinants_test.py
- Added method to obtain circuits for preparation of ground states of quadratic Hamiltonians
- Slightly changed initialization of QuadraticHamiltonian so it doesn't store the antisymmetric part if it's not given
Fixes #94 .
Also, I must admit that I cheated on the tests for the ground state circuits; the test only checks that they run without producing errors, and not that the circuit actually produces the ground state. I plan to write code to produce the ground state from the circuit so that this can be tested, but I'm still thinking about the best way to do this; it might involve using ProjectQ, which I'm not familiar with yet. Specifically, I don't want to write extra code that converts the circuit to sparse matrix operations if there's a more elegant way to do it. I'm okay with this …
> Ground state preparation circuits for QuadraticHamiltonian

- src/openfermion/utils/_channel_state.py
- src/openfermion/utils/_channel_state_test.py
Adds option to specify "all" for target_qubit such that depolarizing channel will act as the totally depolarizing channel, mapping to the identity.
> Adds totally depolarizing channel to existing depolarizing channel

- src/openfermion/utils/_sparse_tools.py
- src/openfermion/utils/_sparse_tools_test.py
I noticed that `jw_hartree_fock_state` could be made more efficient. I actually wrote a more general function `jw_slater_determinant` which lets you instantiate any computational basis vector. I think it's an improvement.
The original function returns a CSR matrix but I noticed that we mostly use CSC so I returned a CSC. Not sure what the policy on that is (if any). Along those lines, I fixed what seems to be a typo in the initialization of `identity_csc`.
> Rewrote jw_hartree_fock_state

- src/openfermion/hamiltonians/_molecular_data.py
I ran into a KeyError when I tried to load some 'old' hdf5 files (when attribute 'general_calculations' wasn't yet implemented in MolecularData).
> Handle KeyError when using 'old' hdf5 files.

- src/openfermion/transforms/_jordan_wigner.py
- src/openfermion/transforms/_reverse_jordan_wigner_test.py
- src/openfermion/utils/_sparse_tools.py
- src/openfermion/utils/_sparse_tools_test.py
One can convert a FermionOperator to a Jordan-Wigner encoded sparse operator by either directly calling `jordan_wigner_sparse`, or by first converting it to a QubitOperator using `jordan_wigner` and then calling `qubit_operator_sparse`. I think these should give the same result, but they don't:
```
In [4]: ferm_op = FermionOperator('1')
In [5]: qubit_op = jordan_wigner(ferm_op)
In [6]: ferm_op_sparse = jordan_wigner_sparse(ferm_op)
In [7]: qubit_op_sparse = qubit_operator_sparse(qubit_op)
In [8]: print(ferm_op_sparse)
(0, 1)	(1+0j)
(2, 3)	(1+0j)
In [9]: print(qubit_op_sparse)
(0, 1)	(1+0j)
(2, 3)	(-1+0j)
```
This bug arises from different conventions being used in `jordan_wigner` and `jordan_wigner_ladder_sparse`. In the first case, the string of Pauli Z's are placed at lower indices …
> Bug in Jordan Wigner ordering

- README.rst
- src/openfermion/ops/_quadratic_hamiltonian.py
- src/openfermion/utils/__init__.py
- src/openfermion/utils/_slater_determinants.py
- src/openfermion/utils/_slater_determinants_test.py
- src/openfermion/utils/_sparse_tools.py
- src/openfermion/utils/_sparse_tools_test.py
- Added `jw_get_quadratic_hamiltonian_ground state`, which computes the ground energy and state of a quadratic Hamiltonian. It can be used instead of `get_ground_state` when possible; it should be faster and more memory efficient. It also serves as a test for the Slater determinant preparation circuits.
- Some minor optimizations and rewriting of Givens rotations code and tests
- Fixed a bug in `get_ground_state` which caused it to return the complex conjugate of the ground state instead of the true ground state.
> Procedure for ground state of quadratic Hamiltonians

- docs/conf.py
- src/openfermion/transforms/_conversion.py
I added a line to the Sphinx configuration. For instance, it changes the documentation of `openfermion.transforms.bravyi_kitaev` to say
>Returns: transformed_operator – An instance of the QubitOperator class
instead of
>Returns: An instance of the QubitOperator class.
>Return type: transformed_operator
which is obviously wrong. I think this is the option we're "supposed" to use according to the way we have been documenting return types. I will add that there are still other issues, like the way the phrase "Instance that captures the" is rendered here: http://openfermion.readthedocs.io/en/latest/openfermion.html#openfermion.transforms.get_molecular_data. This is fixed by starting the description of return values on a new line (I fixed this particular one in this PR). Another thing I'll add …
> Fix Sphinx rendering of return values

- src/openfermion/ops/_quadratic_hamiltonian.py
- src/openfermion/utils/__init__.py
- src/openfermion/utils/_slater_determinants.py
- src/openfermion/utils/_slater_determinants_test.py
- src/openfermion/utils/_sparse_tools.py
- src/openfermion/utils/_sparse_tools_test.py
- I moved `jw_get_gaussian_state` from `utils/_slater_determinants.py` to `utils/_sparse_tools.py`. It seems to fit there better because it returns a sparse matrix. I reverted `get_ground_state` to the original version (without type-checking). You can get a ground state of a QuadraticHamiltonian as a sparse matrix by simply calling `jw_get_gaussian_state` on it.
- I made the Givens rotations docs prettier and added a reference to my arXiv paper where it is explained.
> Minor restructuring and pretty docs

- src/openfermion/hamiltonians/_hubbard.py
- src/openfermion/hamiltonians/_mean_field_dwave.py
- src/openfermion/utils/_trotter_exp_to_qgates_test.py
- Edited the documentation of the Hubbard and mean-field models and moved them from the module header to the actual function so it shows up in the online documentation.
- Fixed what seems to be a bug in the spinless Hubbard model in which the chemical and magnetic potentials aren't added as described in the model description.
> Improved documentation of Hamiltonian models, fix bug in spinless Hubbard model

- src/openfermion/ops/__init__.py
- src/openfermion/ops/_polynomial_tensor.py
There are situations when one may want to use general_basis_change without instantiating a PolynomialTensor object.
> added general_basis_rotation to ops init

- src/openfermion/__init__.py
I don't know if this would be controversial or if this is the best way to achieve this. But when I'm messing around with Jupyter notebooks or on IPython sometimes I find I want to say `from openfermion import *` or `import openfermion`. Of course I would _never_ do such a thing when actually writing a contribution.
> Allow "from openfermion import *"

- src/openfermion/hamiltonians/_molecular_data.py
(fix for my fix)
this is the fix for [issue#14](https://github.com/quantumlib/OpenFermion-Psi4/issues/14) in Openfermion-psi4.
When the hdf5 file is generated from a run_psi4 call with no description, which defaults to '', upon loading at the end of run_psi4, its read as NUL(\x00).
In the following run, the *.inp file is generated with description='.' that raises a TypeError.
> fix for nul description loading

- cloud_library/H_rings_sto-3g_0.7414
- cloud_library/README.md
* Makes cloud library index and gives instructions on how to download / contribute.
* Contains example first dataset (small hydrogen rings example).
Much credit to the amazing @Spaceenter who helped us configure this system.
This is the alpha version of our solution to (https://github.com/quantumlib/OpenFermion/issues/108). I will provide more context there once this is all working as intended.
> first draft of cloud library instructions w/example

- cloud_library/HF_diatomic_sto-3g
* Put file names in a logical order.
* Deleted the file at bond length 0.7414 since that is the equilibrium bond length of H2, not HF.
If you accept this PR, please delete the 0.7414 file from the Cloud prior to merging.
> Ordered data files

- src/openfermion/hamiltonians/_molecular_data.py
Removed an extraneous argument in the documentation of `get_molecular_hamiltonian`.
> Fix documentation in MolecularData

- docs/openfermion.rst
Added a Sphinx option which makes it so that base classes appear under class names in the documentation of `openfermion.ops`. I think this helps address @babbush 's comment in #43 .
> Sphinx show inheritance in openfermion.ops

- src/openfermion/ops/_fermion_operator.py
- src/openfermion/ops/_fermion_operator_test.py
Duplicated terms were not being accounted for; see the test I added.
> Fix bug in FermionOperator multiplication

- src/openfermion/ops/_symbolic_operator.py
- src/openfermion/ops/_symbolic_operator_test.py
I couldn't add commits to #191 because I don't have write access to the main repo, so I'm replacing it with this PR. Some notes on my implementation:
- I added four attributes that all subclasses need to define; see their descriptions in the docstring for SymbolicOperator. So far, the only thing I used the attribute `different_indices_commute` for is to see if we can reorder the factors in terms so that the indices are in ascending order. To get a functioning subclass it's enough to set these four attributes; I removed the uses of abstract base class methods (from the module `abc`) which were introduced in #191.
- The implementation of `__str__` preserves the current string representations for FermionOperators, but would slightly alter those of QubitOperators. Namely, operators would be …
> Add SymbolicOperator and tests

- src/openfermion/utils/_sparse_tools_test.py
Since these tests generate random objects, they were occasionally failing because the object `difference.data` was sometimes empty, which caused errors. I fix that here.
> Fix oversight in random testing

- examples/openfermion_demo.ipynb
- src/openfermion/utils/_trotter_exp_to_qgates.py
- src/openfermion/utils/_trotter_exp_to_qgates_test.py
Minor update to the trotter_exp_to_qgates file, allowing the Rz rotations to be controlled by an ancilla for QPE purposes. Also fixed a bug where passing the identity operator would cause an error.
Now passing the identity passes for time evolution (i.e. it doesn't return a phase gate). Not sure what is preferable here.
> Added possibility for QPE to have rotations controlled by an ancilla

- src/openfermion/transforms/_bksf.py
- src/openfermion/transforms/_bksf_test.py
Removed lines pertaining to the two-unique-indices case. That case is incorrect -- terms with two unique indices should not contribute to the edge operator. Discussed and done with @kanavsetia.
> Updated _bksf.py

- examples/openfermion_demo.ipynb
- src/openfermion/hamiltonians/__init__.py
- src/openfermion/hamiltonians/_hubbard.py
- src/openfermion/hamiltonians/_mean_field_dwave.py
- src/openfermion/measurements/_equality_constraint_projection.py
- src/openfermion/ops/__init__.py
- src/openfermion/ops/_fermion_operator.py
- src/openfermion/ops/_fermion_operator_test.py
- src/openfermion/transforms/_jordan_wigner_test.py
- src/openfermion/utils/__init__.py
- src/openfermion/utils/_commutators_test.py
- src/openfermion/utils/_operator_utils.py
- src/openfermion/utils/_operator_utils_test.py
- src/openfermion/utils/_sparse_tools.py
- Allow `hermitian_conjugated` to be applied to QubitOperators
- Move it from `ops/_fermion_operator.py` to `utils/_operator_utils.py`
> Generalize hermitian_conjugated and move it to operator_utils

- src/openfermion/__init__.py
- src/openfermion/ops/__init__.py
- src/openfermion/ops/_fermion_operator.py
- src/openfermion/ops/_interaction_rdm.py
- src/openfermion/ops/_quadratic_hamiltonian.py
- src/openfermion/utils/__init__.py
- src/openfermion/utils/_sparse_tools.py
- Removed some in-line `import` statements that are no longer necessary because of improved import ordering in some `__init__.py` files
- Alphabeticized some imports
- Made it so that `from openfermion import *` doesn't also import `EQ_TOLERANCE` from `config.py`. I think generally users generally expect `*` imports to import only functions and not constants. Anyway I originally only added it because I thought it was necessary to make some things work but I think I was mistaken.
- Fix sphinx warnings
> Clean up import statements and fix sphinx warnings

- examples/openfermion_demo.ipynb
Currently the section on MolecularData says "There may be plugins available in future" but there are plugins available now so I added references to them.
> add to demo references and links to electronic structure plugins

- src/openfermion/utils/_unitary_cc.py
The function `uccsd_singlet_paramsize` should return an integer.
> Use integer division in uccsd paramsize

- src/openfermion/ops/_quadratic_hamiltonian_test.py
- src/openfermion/transforms/_verstraete_cirac.py
- src/openfermion/utils/_special_operators.py
- src/openfermion/utils/_special_operators_test.py
Resolves #258 .
Also switched the meaning of "Type 0" and "Type 1" operators, and allows initialization using strings, e.g. `majorana_operator('c3')` now means Type 0 operator on mode 3.
> Change normalization and initialization of Majorana operators.

- src/openfermion/utils/__init__.py
- src/openfermion/utils/_unitary_cc.py
- src/openfermion/utils/_unitary_cc_test.py
I'm a bit unsure about this one, but hopefully my variable names are clear enough that someone can follow my reasoning and correct me if I'm wrong.
Singlet implies Sz = 0, which means there are the same number of spin up as spin down electrons, which means the number of electrons is even, right?
Previously we had `n_single_amplitudes = n_occupied * n_virtual`, but since `n_occupied` and `n_virtual` refer to spatial orbitals, we need to double it because there are two spins, right?
Then, we had `n_double_amplitudes = n_single_amplitudes ** 2`. But we wouldn't want to count double excitations of the same electron, or for two electrons into the same orbital, etc., right?
If I'm right about this I think we may want to change `uccsd_singlet_operator` as well (I don't mind doing it).
> Fix uccsd_singlet_paramsize?

- src/openfermion/utils/_unitary_cc.py
- src/openfermion/utils/_unitary_cc_test.py
@jarrodmcc I messed up yesterday and added a redundant double excitation. I momentarily forgot that electrons are indistinguishable!
> Remove redundant double excitation from UCCSD singlet generator

- examples/openfermion_demo.ipynb
- src/openfermion/hamiltonians/_jellium_test.py
- src/openfermion/hamiltonians/_plane_wave_hamiltonian_test.py
- src/openfermion/ops/_fermion_operator_test.py
- src/openfermion/ops/_quadratic_hamiltonian_test.py
- src/openfermion/ops/_qubit_operator_test.py
- src/openfermion/ops/_symbolic_operator.py
- src/openfermion/ops/_symbolic_operator_test.py
- src/openfermion/tests/_hydrogen_integration_test.py
- src/openfermion/tests/_lih_integration_test.py
- src/openfermion/transforms/_binary_code_transform_test.py
- src/openfermion/transforms/_binary_codes_test.py
- src/openfermion/transforms/_bksf_test.py
- src/openfermion/transforms/_bravyi_kitaev_test.py
- src/openfermion/transforms/_conversion_test.py
- src/openfermion/transforms/_jordan_wigner_test.py
- src/openfermion/transforms/_reverse_jordan_wigner_test.py
- src/openfermion/utils/_commutators_test.py
- src/openfermion/utils/_hubbard_trotter_error_test.py
- src/openfermion/utils/_low_depth_trotter_error.py
- src/openfermion/utils/_low_depth_trotter_error_test.py
- src/openfermion/utils/_operator_utils.py
- src/openfermion/utils/_operator_utils_test.py
- src/openfermion/utils/_special_operators_test.py
- src/openfermion/utils/_trotter_error.py
- src/openfermion/utils/_trotter_error_test.py
- src/openfermion/utils/_unitary_cc_test.py
This change was discussed at #233 . After this is merged, `op1.isclose(op2)` is no longer valid syntax and `op1 == op2` should be used instead, where `op1` and `op2` are SymbolicOperators such as FermionOperator or QubitOperator.
I did not define `__neq__` yet. I will do that once this and #233 are merged, then use EqualsTester to reformulate some tests for `__eq__` (which will also test `__neq__`).
> Define __eq__ for SymbolicOperator and eliminate isclose

- src/openfermion/ops/_symbolic_operator.py
- src/openfermion/ops/_symbolic_operator_test.py
- Define `__neq__` for SymbolicOperator and add tests
- Allow `__eq__` for SymbolicOperator to be applied to an operator of a different type (returns `False`).
- Add back `isclose` with a DeprecationWarning
> Define __neq__ for SymbolicOperator, add tests, add back isclose with DeprecationWarning

- src/openfermion/ops/_symbolic_operator.py
- src/openfermion/ops/_symbolic_operator_test.py
Often I want to initialize something with a single factor like `QubitOperator('X0')` but programmatically so I need to use a tuple, like `QubitOperator(((0, 'X'),))` and I find it very annoying to have to type out the parentheses and second comma. So this PR lets you initialize it using `QubitOperator((0, 'X'))` instead.
Yes/No?
> Allow initialization of SymbolicOperator with single factor

- src/openfermion/ops/_symbolic_operator.py
- src/openfermion/ops/_symbolic_operator_test.py
I messed up; "raising" a warning causes the program to terminate and the correct way to do it is to use the `warnings` module.
> Don't "raise" warning

- src/openfermion/utils/_testing_utils.py
- src/openfermion/utils/_testing_utils_test.py
I'm investigating a bug and found it useful to understand this function. I couldn't so I rewrote it and added an option to generate a complex operator, and tested it as well.
However, I'm a little confused about the exposition of symmetries in InteractionOperator from the OpenFermion paper, specifically the `h_{pqrs} = h_{sqrp} = ...`. Are these symmetries derived only from the hermiticity of the Hamiltonian? If so, then I don't see why, for instance, `h_{pqrs} = h_{prqs}`; if r and q are different I think these should be the negative of each other. I think the symmetries implied from my code are correct.
> Rewrite random_interaction_operator and allow complex option

- src/openfermion/transforms/_bksf.py
- src/openfermion/transforms/_jordan_wigner.py
- src/openfermion/transforms/_jordan_wigner_test.py
- src/openfermion/utils/_operator_utils_test.py
Fixes #281 .
Instead of finding the bug I just rewrote the code. It's also now about 4x faster than the old (incorrect) code.
One thing I noticed and documented is that based on the way the helper functions `jordan_wigner_one_body` and `jordan_wigner_two_body` are written, this only supports InteractionOperators with real entries. Maybe a future PR can expand support to complex ones.
> Fix Jordan Wigner for InteractionOperator

- src/openfermion/utils/_operator_utils.py
- src/openfermion/utils/_operator_utils_test.py
It was giving false negatives due to not normal-ordering.
> fix bug in is_hermitian for FermionOperators

- src/openfermion/ops/_diagonal_coulomb_hamiltonian.py
- src/openfermion/ops/_diagonal_coulomb_hamiltonian_test.py
- src/openfermion/ops/_polynomial_tensor.py
- src/openfermion/ops/_polynomial_tensor_test.py
- src/openfermion/utils/_testing_utils.py
- Allows multiplying and dividing PolynomialTensors and DiagonalCoulombHamiltonians by numbers
- Fixed incorrect behavior in multiplication by a PolynomialTensor with different key (a missing key should count as the zero tensor; previous behavior was the same as adding zeros instead of multiplying zeros).
> Fix PolynomialTensor multiply, extend to floats, and allow dividing by numbers

- src/openfermion/utils/_operator_utils.py
- src/openfermion/utils/_operator_utils_test.py
> Added human-readable file IO for SymbolicOperators

- src/openfermion/ops/_givens_rotations_test.py
- src/openfermion/ops/_quadratic_hamiltonian.py
- src/openfermion/ops/_quadratic_hamiltonian_test.py
- src/openfermion/utils/_slater_determinants.py
Changes the `diagonalizing_bogoliubov_transform` method of QuadraticHamiltonian to return an Nx(2N) matrix describing the new creation operators instead of a (2N)x(2N) matrix describing both the creation and annihilation operators in the case that the Hamiltonian does not conserve particle number. This form is less redundant and also matches up more closely with the format of the matrix returned when the Hamiltonian does conserve particle number (NxN, describing the new creation operators).
> Return non-redundant Bogoliubov transformation matrix

- src/openfermion/ops/_binary_code.py
- src/openfermion/ops/_binary_code_test.py
- src/openfermion/ops/_binary_polynomial.py
- src/openfermion/ops/_binary_polynomial_test.py
- src/openfermion/ops/_fermion_operator.py
- src/openfermion/ops/_fermion_operator_test.py
- src/openfermion/ops/_givens_rotations_test.py
- src/openfermion/ops/_interaction_operator.py
- src/openfermion/ops/_interaction_operator_test.py
- src/openfermion/ops/_interaction_rdm.py
- src/openfermion/ops/_interaction_rdm_test.py
- src/openfermion/ops/_polynomial_tensor.py
- src/openfermion/ops/_polynomial_tensor_test.py
- src/openfermion/ops/_quadratic_hamiltonian.py
- src/openfermion/ops/_quadratic_hamiltonian_test.py
- src/openfermion/ops/_qubit_operator.py
- src/openfermion/ops/_qubit_operator_test.py
- src/openfermion/ops/_symbolic_operator.py
- src/openfermion/ops/_symbolic_operator_test.py
- src/openfermion/utils/_slater_determinants.py
- Fixed an error in the documentation of `QuadraticHamiltonian.bogoliubov_transform`.
- Removed lint caught by `pycodestyle` and my `pylint` in `ops`.
> Fix docs errors and lint in ops

- src/openfermion/utils/_lcu_util.py
- src/openfermion/utils/_lcu_util_test.py
Previously, the code would pick denominators that weren't powers of 2 (times the number of items). Powers of 2 are preferable because then the subsampling value can be generated with just Hadamard gates, instead of a more complicated Uniform_K circuit.
> Fix preprocess_lcu_coefficients_for_reversible_sampling not picking a power of 2 when discretizing

- src/openfermion/ops/_givens_rotations.py
- src/openfermion/ops/_givens_rotations_test.py
One of the optimizations used in the Givens rotation code is to use standard rotation matrices when dealing with only real numbers, but the check for whether a number is real should be satisfied with approximate real-ness.
> Use EQ_TOLERANCE to check for real numbers in Givens rotations code

- src/openfermion/utils/_sparse_tools.py
- src/openfermion/utils/_sparse_tools_test.py
I don't think there's a good way to check if a LinearOperator is Hermitian, and in any case I'm not sure this is the place to be checking for that.
> Allow get_ground_state to be applied to LinearOperators

- src/openfermion/utils/_sparse_tools.py
- src/openfermion/utils/_sparse_tools_test.py
This's to get the diagonal elements for the matrix only, which is a critical input for Davidson algorithm.
See one reference at:
http://people.inf.ethz.ch/arbenz/ewp/Lnotes/chapter12.pdf
> Add get_lienar_qubit_operator_diagonal to be used for Davidson algorithm.

- src/openfermion/transforms/_conversion.py
- src/openfermion/transforms/_conversion_test.py
For instance, this lets you call `get_quadratic_hamiltonian` on a FermionOperator that contains non-quadratic terms, with the result that only the quadratic terms are considered. Similarly for `get_diagonal_coulomb_hamiltonian`. The default behavior is still the same (raise an error if incompatible terms are encountered).
> Add option to ignore incompatible terms when converting to DiagonalCoulombHamiltonian or QuadraticHamiltonian

- README.rst
This is a small pull request, to add SFOpenFermion to the list of OpenFermion plugins.
> Added SFOpenBoson to the list of OpenFermion plugins

- MANIFEST.in
- setup.py
- src/openfermion/tests/_example_test.py
- src/openfermion/utils/__init__.py
- src/openfermion/utils/_pubchem.py
- src/openfermion/utils/_pubchem_test.py
- src/openfermion/utils/_testing_utils.py
> test installed module

- README.rst
- docs/other_projects.md
Adds a page to collect project and papers using OpenFermion that hopefully both inspire new projects and let people advertise their own work using OpenFermion there.  I left all the links as ArXiv so that people don't need journal descriptions to see the papers.
> Add page in docs for collecting projects and papers

- src/openfermion/utils/_low_rank.py
- src/openfermion/utils/_low_rank_test.py
* Fixes an error where I was performing truncation only based on eigenvalue and failing to take into account the norm of the eigenvector.
* Allows one to truncate by specifying the final rank of the decomposed operator.
> Low rank options

- src/openfermion/utils/_low_rank_test.py
- src/openfermion/utils/_testing_utils.py
- src/openfermion/utils/_testing_utils_test.py
Calling a function like `random_interaction_operator(5)` twice in a row should not return the same object. Tests should explicitly set the seeds, preferably to random-ish values.
Also fixes an issue where `random_interaction_operator` always uses the same one-body tensor and other related issues.
> fix RNG seeding in testing functions

- src/openfermion/ops/_symbolic_operator.py
- src/openfermion/ops/_symbolic_operator_test.py
This gives SymbolicOperator a consistent string representation. Among other benefits, it makes it possible to make tests based on the string output.
> Sort SymbolicOperator terms for string output

- src/openfermion/hamiltonians/_molecular_data.py
- src/openfermion/utils/__init__.py
- src/openfermion/utils/_low_rank.py
- src/openfermion/utils/_low_rank_test.py
Adds a low-rank decomposition that acts on the spatial orbitals, which can take advantage of the PSD symmetry more effectively.  Also corrects a fundamental conflation of integral and fermionic symmetry in the promotion from spatial to spin integrals in the original molecular data structure.
> Spatial low rank

- docs/other_projects.md
I added the link to the Projects and Papers page for the implementation of the CUSP protocol (that uses both OpenFermion and Cirq).
> Add CUSP to Projects page.

- requirements.txt
The spatial low rank routine in `utils/_low_rank.py` uses `scipy.linalg.ldl`, which was introduced in Scipy version 1.1.0, which is the latest version.
https://docs.scipy.org/doc/scipy-1.1.0/reference/generated/scipy.linalg.ldl.html#scipy.linalg.ldl
> Update scipy requirement to 1.1.0

- src/openfermion/__init__.py
- src/openfermion/utils/_testing_utils.py
- src/openfermion/utils/_testing_utils_test.py
Setting `expand_spin` to True will cause each orbital to be expanded symmetrically into two (so the input number of orbitals is taken to refer to spatial orbitals).
> Add option to generate random InteractionOperators with spin symmetry

- requirements.txt
- src/openfermion/hamiltonians/_jellium.py
- src/openfermion/utils/_low_rank.py
- src/openfermion/utils/_low_rank_test.py
Fixes #427 .
It's necessary to check whether the matrices are Hermitian (and use eig if they're not) in order to pass the tests of the non-spatial routine.
> Diagonalize one-body matrix using eigh and in spatial basis for low rank decomposition

- README.rst
*Removed OpenFermion-ProjectQ from list of actively maintained plugins.
Note that the OpenFermion-ProjectQ repository will be archived. If any responsible developers would like to maintain OpenFermion-ProjectQ, contact us. We'd be happy to transfer that repo to your control so that open source development can continue. But we do not have the resources to continue to maintain it.
> deprecated OpenFermion-ProjectQ

- src/openfermion/utils/_diagonal_coulomb_trotter_error.py
- src/openfermion/utils/_diagonal_coulomb_trotter_error_test.py
Computes Trotter error operators for both the split-operator and fermionic swap network Trotter steps.
The fermionic swap network functionality covers the same use cases as in https://github.com/quantumlib/OpenFermion/blob/master/src/openfermion/utils/_low_depth_trotter_error.py, though the new code is quite a bit faster. That code is much simpler, so I'm not sure we should replace it outright, though we probably could. The new split-operator code uses similar tricks to get a comparable speedup, though evaluating the split-operator Trotter error should be easier in general since there are effectively only two terms in the Trotter ordering.
The highest speedup I've seen so far in testing is ~200x for the 32x32 Hubbard model.
> Masking + caching for evaluating errors for different Trotter steps

- src/openfermion/utils/_diagonal_coulomb_trotter_error.py
- src/openfermion/utils/_low_depth_trotter_error.py
- src/openfermion/utils/_low_depth_trotter_error_test.py
In the low-depth Trotter steps, we might want to choose whether the rotations from the external potential are interspersed throughout the other terms, or all placed at the end. This PR adds that functionality + some small other refactoring/variable name changes.
> Added ability to choose where external potential rotations are placed

- docker/README.md
- docker/dockerfile
- Replaces ProjectQ and OpenFermion-ProjectQ with Cirq and OpenFermion-Cirq
- Installs quantumlib packages from PyPI rather than the GitHub repos
- Installs Python 3 instead of Python 2
- Installs Python 3 version of Psi4 instead of Python 2 version
- Updates the README
> Update Docker image

- src/openfermion/hamiltonians/_hubbard.py
This fixes the doc to match what the code actually does. However, I have a question. The original doc seemed to assume that the spinless model would be defined on a one-dimensional (rather than two-dimensional) lattice. Is that because the spinless model is only studied in 1d and not in 2d? In that case we should actually be modifying the source code, rather than the documentation.
> Fix spinless Hubbard model doc

- src/openfermion/_version.py
- src/openfermion/hamiltonians/_hubbard.py
- src/openfermion/hamiltonians/_hubbard_test.py
I broke up the giant "general" Hubbard model function into separate functions for Bose-, spinful Fermi-, and spinless Fermi-Hubbard models, defining some helper functions used throughout. I think this greatly improves the source code readability.
> Refactor Hubbard module

- src/openfermion/utils/_linear_qubit_operator_test.py
It was failing on machines with fewer than 10 CPUs
> Fix LinearQubitOperator cpu count test

- src/openfermion/utils/_linear_qubit_operator_test.py
They were assuming that the tests would be run on a machine with at least 6 and at most 20 cpus.
> Fix linear qubit operator tests being machine-dependent

- README.rst
The MyBinder website provides free, cloud-based hosting of jupyter notebooks, built from public git repos!! :)
I was able to just enter this repo's URL into the builder on https://mybinder.org/, and it correctly set up the repo based on the Dockerfile and everything seems to work! :) This means with one-click, people can open a browser-based environment and start interacting with the tutorial! :)
Sorry i've never contributed to this Repo before, but i was curious to try this out. The easiest way for me to get started was to plug it in to MyBinder, and so i thought i'd share that back with you!!
> Add README link to run Example Notebooks in MyBinder

- src/openfermion/ops/_interaction_operator.py
The documentation for the interationOperator appearted to be
missing some math mode specifiers.  I've added those. The
mathematical form for the operator is no properly displayed
and the format for the one and two body integrals in the that
show up in the documentation agree with that formatting.
> Documentation fixes for openfermion.ops._interaction_operator

- src/openfermion/hamiltonians/_jellium.py
Exploits translation invariance in construction of Jellium hamiltonian in dual basis, which also impacts construction of any chemical / material system in the dual basis.  Speedup is roughly a factor of N in the size of the basis.
Could probably get further speedups by making routines which create the diagonal hamiltonian matrices directly instead of building fermion operators.
> Utilize translation invariance in construction of jellium Hamiltonian

- src/openfermion/ops/__init__.py
- src/openfermion/ops/_majorana_operator.py
- src/openfermion/ops/_majorana_operator_test.py
> Define MajoranaOperator

- src/openfermion/ops/_interaction_operator.py
- src/openfermion/ops/_interaction_operator_test.py
- src/openfermion/ops/_polynomial_tensor.py
- src/openfermion/ops/_polynomial_tensor_test.py
- src/openfermion/utils/_operator_utils.py
- src/openfermion/utils/_operator_utils_test.py
handled by normal_ordered, is_hermitian, and hermitian_conjugate
new zero construction method
new projection method
> adds InteractionOperator utilities

- NOTICE
- README.rst
- src/openfermion/utils/_qubit_tapering_from_stabilizer.py
- src/openfermion/utils/_qubit_tapering_from_stabilizer_test.py
We update the tapering qubits using stabilizer function to deal with cases where the stabilizers have larger weight than the Hamiltonian.
In principle, this will be useful to study subgroups of Pauli strings belonging to a larger Hamiltonian.
Additionally, I added myself in the author list after an email from @babbush to @msteudtner. I followed the alphabetic order.
Best,
Xavi and Mark
> Upgrade tapering qubit function

- src/openfermion/transforms/_qubit_operator_transforms.py
- src/openfermion/transforms/_qubit_operator_transforms_test.py
Hi all,
After some discussion with the user @rugantio I decided to improve the existing functions project_onto_sector and projection_error.
The main enhancement consists on checking that the sectors are passed as 0 or 1 (which is clearly documented) instead of 1 or -1.
Additionally, I added some trivial assertions and update the test such that the assertions are tested.
Please, let me know if anything else is required.
PS: A previous PR didn't have the commits, sorry.
Best,
Xavi
> Enhancement of Project onto sector function.

- examples/openfermion_tutorial.ipynb
- src/openfermion/measurements/__init__.py
- src/openfermion/measurements/_qubit_partitioning.py
- src/openfermion/measurements/_qubit_partitioning_test.py
An implementation of the partial state tomography methods for qubits that we introduced in https://arxiv.org/pdf/1908.05628.pdf .
> Added qubit partition functions

- src/openfermion/utils/_pubchem.py
- src/openfermion/utils/_pubchem_test.py
Currently, the function **geometry_from_pubchem** in **utils/_pubchem.py/** constructs the geometry of a molecule based on 3D structure info if available, otherwise the 2D structure info is used. If both 3D and 2D info are not available in PubChem, None is returned.
In this pull request I have implemented a new argument for this functiion: structure. With this argument users of the function will be able to request _only 3D_ or _only 2D_ information. The default behavior of the function is unchanged, i.e. if the 'structure' argument is not specified, the function will behave as before this pull request, for backwards compatibility.
The reason for the implementation of this argument is, that for a bunch of molecules, the 2D structure information has nothing to do with the actual geometric …
> Add functionality to retrieve specific types of structure info from PubChem

- src/openfermion/hamiltonians/_molecular_data.py
This modification avoids OSError when current directory and
openfermion/data directory are not on the same filesystem.
Following code is minimal sample to reproduce the problem.
If OpenFermion installed directory and current directory are on the same filesystem,
this code works without any errors.
However, if they're not on the same filesystem, error occurs.
```py
from openfermion import MolecularData
m = MolecularData([['Li', [0, 0, 0]], ['H', [0, 0, 0.7414]]], 'sto-3g', 1, 0, 'test')
m.save()
```
Error:
```
Traceback (most recent call last):
File "bad.py", line 3, in <module>
m.save()
File "/usr/local/lib/python3.6/dist-packages/openfermion/hamiltonians/_molecular_data.py", line 642, in save
"{}.hdf5".format(self.filename))
OSError: [Errno 18] Invalid cross-device link: …
```
> Use shutil.move instead of os.rename

- src/openfermion/utils/__init__.py
- src/openfermion/utils/_reduced_hamiltonian.py
- src/openfermion/utils/_reduced_hamiltonian_test.py
The reduced Hamiltonian has only two-body fermionic correlators.  In the
N-particle space this is an isospectral operator to the original Hamiltonian.
> Construct reduced Hamiltonian

- dev_tools/docs/build_api_docs.py
Puts `api_docs` build script similar to the ones in Cirq, copied from TFQ. @lamberta I've tested this locally and it should be good to go to be iterated on.
> Added build_api_docs.py script

- cloud_library/k-acene.txt
Adding k-acenes to the cloud library.  pi active spaces are 4k + 2o, 4k + 2e in size.
Integrals for the active space are stored in the integral fields of MolecularData.
The MO-coefficients from pyscf are stored in the general_calculations field.
Email: rubinnc0@gmail.com
> Oligoacene addition to cloud library

- setup.py
Fixes: https://github.com/quantumlib/OpenFermion/issues/644
Tested in Colab:
```
!pip install -U git+https://github.com/lamberta/OpenFermion.git@setup-docs#egg=openfermion
...
from openfermion.ops import FermionOperator
my_term = FermionOperator(((3, 1), (1, 0)))
print(my_term)
my_term = FermionOperator('3^ 1')
print(my_term)
```
> Update setup.py data_files to point to docs/tutorials/

- README.rst
OFC will be depricated and all functionality is now in
OpenFermion proper.
> Remove mention of OFC

- docs/_book.yaml
When OpenFermion-Cirq was merged we gained those tutorials.
The list in docs is now updated and reordered.
> Update tutorial list

- requirements.txt
- src/openfermion/circuits/gates/fermionic_simulation_test.py
- src/openfermion/circuits/gates/four_qubit_gates_test.py
- src/openfermion/circuits/primitives/bogoliubov_transform_test.py
- src/openfermion/circuits/primitives/ffft_test.py
- src/openfermion/circuits/primitives/optimal_givens_decomposition_test.py
- src/openfermion/circuits/primitives/state_preparation_test.py
- src/openfermion/circuits/trotter/simulate_trotter_test.py
- src/openfermion/transforms/opconversions/qubitoperator_to_paulisum_test.py
- src/openfermion/utils/bch_expansion_test.py
- src/openfermion/utils/channel_state_test.py
Updated test files now use `final_state_vector`.  Old function call
will be depricated in cirq  v0.10.
> Update cirq pin

- src/openfermion/.vscode/settings.json
- src/openfermion/hamiltonians/jellium.py
- src/openfermion/hamiltonians/mean_field_dwave.py
- src/openfermion/hamiltonians/plane_wave_hamiltonian.py
- src/openfermion/hamiltonians/special_operators.py
- src/openfermion/hamiltonians/special_operators_test.py
I added type hints to the function parameters and for the function return for some files in Hamiltonians.
I also noticed that the parity parameter is expected to take a value of -1 or 1. It doesn't check whether the actual value is either one of those. It will now throw a ValueError for other values.
> Type hints hamiltonians

- dev_tools/docs/build_api_docs.py
This file is required to build the reference docs at https://quantumai.google/reference/python/openfermion/all_symbols
Accidently deleted in https://github.com/quantumlib/OpenFermion/pull/695
> Restore build_api_docs.py file for API doc gen.

- src/openfermion/linalg/rdm_reconstruction_test.py
- src/openfermion/linalg/sparse_tools.py
- src/openfermion/linalg/sparse_tools_test.py
scipy sparse now does not infer the highest datatype.
The user must pass the correct dtype for the data to be cast.
> Fix scipy dtype errors

- README.rst
- requirements.txt
- src/openfermion/circuits/gates/fermionic_simulation.py
Citation now references published paper.  Cirq version is now pinned to new release.
> Update cirq version and citation

- dev_tools/conf/pip-list-dev-tools.txt
- dev_tools/prepared_env.py
- requirements.txt
- src/openfermion/_compat_test.py
- src/openfermion/conftest.py
- src/openfermion/measurements/vpe_estimators.py
Upgrades to cirq 0.11. `cirq.TrialResult` was removed after two releases worth of deprecation. I also added a new env var to pytest's conftest.py that will fail tests if a deprecated Cirq functionality is used. Also, mypy was failing to install on Mac + Python 3.8, so I bumped that too.
> Upgrade to cirq 0.11

- src/openfermion/_compat_test.py
I noticed that I made a mistake - the deprecation test was always passing. Now it's only passing if the `CIRQ_TESTING` env var is defined - which is what we want.
> make deprecation test meaningful

- requirements.txt
Use "compatible release" spec. This is important because
we use requirements.txt to set install_requires
> Loosen Cirq version pinning

- README.rst
I noticed that we aren't advertising OpenFermion-FQE here. But we should be right? Feel free to edit aspects of the description.
> Adding mention of OpenFermion-FQE to the frontpage

- .github/workflows/ci.yml
- .github/workflows/nightly.yml
- requirements.txt
- Use CI "matrix" to reduce duplication in testing infrastructure
- stop pinning cirq in `install_requires`. Lower bound only. More often than not, we are artificially restricting dependers from using the latest Cirq than preventing real problems. Testing against pre-release should prevent surprises.
- Test 1) lowest supported version of things 2) latest version of things 3) vs. cirq pre-release
- Clarify and bump supported python version: latest two versions
- Clarify and bump supported cirq version: latest two versions (unless this is difficult to maintain, then we'd just support the latest version and drop it from the matrix)
> Revamp CI: matrix, multi-Cirq

- src/openfermion/_compat_test.py
- src/openfermion/hamiltonians/__init__.py
- src/openfermion/hamiltonians/richardson_gaudin.py
- src/openfermion/hamiltonians/richardson_gaudin_test.py
- src/openfermion/ops/operators/symbolic_operator.py
- src/openfermion/ops/representations/doci_hamiltonian.py
- src/openfermion/ops/representations/doci_hamiltonian_test.py
This PR aims to facilitate the use of reduced Bardeen-Cooper-Schrieffer Hamiltonians. Although these Hamiltonians are exactly solvable using the Richardson-Gaudin equations, are useful for serving as a benchmark for strongly correlated systems where the attractive regime is prominent and the equations break down, while maintaining a simple form, allowing for easier implementation in NISQ devices where the connectivity between qubits remains an important factor.
@ncrubin please share your thoughts and feedback on this.
> Reduced BCS type Hamiltonians

- src/openfermion/testing/wrapped.py
- Add additional parameter to ignore gates that do not decompose
into cirq native gates (such as fermionic quartic gates).
> Fix cirq coverage test

- docs/tutorials/circuits_3_arbitrary_basis_trotter.ipynb
DeprecationWarning: DropNegligible was used but is deprecated. It will be removed in cirq v1.0. Use cirq.drop_negligible_operations instead.
cirq.DropNegligible().optimize_circuit
cirq.drop_empty_moments / cirq.drop_negligible_operations: Removes moments that are empty or operations that have very small effects, respectively.
> DropNegligible was used but is deprecated.

- README.rst
The OpenFermion/Q-Chem plugin was developed by Yongbin Kim and Anna Krylov (University of Southern California)
> Adds a link to the Q-Chem plugin in README

- src/openfermion/transforms/opconversions/jordan_wigner.py
Low-hanging fruit for a simple speedup when working on `FermionOperator` -> `QubitOperator` conversions. The problem has been raised in #587. This is not an optimal solution to this issue (neither parallelization nor cython), but there is a significant speed improvement when working with a `FermionOperator` with redundant terms.
Here is a simple script I used to test:
```
import time
import openfermion as of
from openfermionpyscf import run_pyscf
mol = of.chem.MolecularData(geometry=[["H", (0., 0., 0.)], ["H", (0., 0., 0.75)]], multiplicity=1, charge=0, basis="ccpvtz")
mol = run_pyscf(mol, verbose=True)
mol_op = mol.get_molecular_hamiltonian()
ferm_op = of.transforms.get_fermion_operator(mol_op)
start_time = time.time()
qubit_op = of.transforms.jordan_wigner(ferm_op)
final_time = …
```
> Lookup dictionary for JW transformation of a FermionOperator

- requirements.txt
Cirq has had a lot of movement in preparation for the 1.0 release.
OpenFermion now only works with versions of cirq <=0.14.0.  This
PR enforces python package management into the allowable cirq range.
This PR should be followed by a permenant fix for cirq 1.0
compatability.
> Pin Requirements to working cirq versions

- src/openfermion/circuits/primitives/ffft.py
- This is breaking one of the openfermion notebooks.
> Fix reference to deprecated SingleQubitGate

- .github/workflows/ci.yml
- requirements.txt
- src/openfermion/circuits/primitives/bogoliubov_transform_test.py
- src/openfermion/circuits/primitives/ffft_test.py
With the removal of final_state_vector from the Circuit object
we move the final_state_vector to the simulator.simulate result.
update requirements and CI
pin to cirq 1.0
unpin from 1.0
update ci workflow
bump min version in CI since 3.6 is no longer supported
> Making OF compatible with cirq>0.15

- src/openfermion/_version.py
- src/openfermion/circuits/gates/four_qubit_gates_test.py
- src/openfermion/testing/circuit_validation.py
Apparently prior releases of openfermion were attempting to
use scipy.linalg.expm to exponentiate sparse matrices.  Until recently
the scipy API seem to resolve the issue of using scipy.linalg.expm
instead of scipy.sparse.linalg.expm.
This issue was not surfaced until the 1.0.0dev release so some
combination of numpy/scipy pinning or depinning has revealed this
bug in openfermion.  This commit fixes the issue by converting
scipy.linalg.expm to scipy.sparse.linalg.expm where appropriate.
> Resolves failing cirq pre-release

- docs/tutorials/circuits_1_basis_change.ipynb
- docs/tutorials/circuits_2_diagonal_coulomb_trotter.ipynb
- These two were using pre-Cirq 1.0 formalisms.
- Change cirq.DropNegligble to cirq.drop_negligible_operations
- Change cirq_google.optimized_for_xmon to
cirq.optimize_for_target_gateset
> Fix two openfermion docs

- docs/fqe/tutorials/diagonal_coulomb_evolution.ipynb
- docs/fqe/tutorials/fermi_hubbard.ipynb
- docs/fqe/tutorials/fqe_vs_openfermion_quadratic_hamiltonians.ipynb
- The matrix exponential of these sparse matrices is causing errors in certain versions of scipy:
"loop of ufunc does not support argument 0 of type csc_matrix which has no callable exp method"
- Converting these to dense matrices to get docs working again.
Note:  this does have a performance impact on the code.  Is there a better way to do this?
> Matrix exponential of sparse matrix is not allowed

- docs/fqe/tutorials/fermi_hubbard.ipynb
- Taking exponential of a sparse matrix is no longer allowed.
- Convert this to dense matrix to fix doc generation.
> Fix another expm doc error

- check/format-incremental
- dev_tools/requirements/deps/format.txt
- copy `check/format-incremental` from Cirq (one minor edit to remove an unnecessary exclude line)
- copy `black` version pin from Cirq so our open-source dev environments are mildly in sync.
Instead of formatting everything all at once, I plan on just letting the formatting change slowly over time as PRs format only their changed files. cc @ncrubin @fdmalone @tanujkhattar
> Switch to using the black formatter

- src/openfermion/hamiltonians/jellium.py
- src/openfermion/linalg/davidson_test.py
- src/openfermion/transforms/opconversions/bksf_test.py
- src/openfermion/utils/grid.py
The diff is huge because of reformatting. May be worth first merging #846.  But just fixed some deprecation warnings (numpy.product, numpy.math, converting size one array to scalar)  emitted by pytest.
> Fix pytest deprecation warnings.

- dev_tools/requirements/deps/runtime.txt
- dev_tools/requirements/envs/dev.env.txt
- dev_tools/requirements/envs/format.env.txt
- dev_tools/requirements/envs/mypy.env.txt
- dev_tools/requirements/envs/pip-tools.env.txt
- dev_tools/requirements/envs/pylint.env.txt
- dev_tools/requirements/envs/pytest-extra.env.txt
- dev_tools/requirements/envs/pytest.env.txt
- dev_tools/requirements/max_compat/dev.env.txt
- dev_tools/requirements/max_compat/pytest-max-compat.env.txt
- src/openfermion/circuits/gates/fermionic_simulation.py
Addresses #815 by replacing la.sqrtm with the square root computed via eigendecomposition. Just bumping the input array's precision to 256 didn't solve the problem.
> Fix scipy sqrtm precision issue

- src/openfermion/ops/operators/majorana_operator.py
- src/openfermion/ops/operators/majorana_operator_test.py
Addition and subtraction in MajoranaOperator accept a number as an input.
Bugs in `__isub__` and the corresponding testcases are fixed.
Related to [this issue](https://github.com/quantumlib/OpenFermion/issues/862#issue-2084048358).
> MajoranaOperator supports operation with numbers.

- docs/fqe/tutorials/fermi_hubbard.ipynb
This document errors out with the following error:
"RuntimeError: maximum taylor expansion limit reached"
Changing the time to 0.9 eliminates the error.  Better solutions or ideas welcome, but this at least allows the python notebooks to be generated.
> Fix doc generation

- docs/tutorials/circuits_1_basis_change.ipynb
cirq_google is not used in this tutorial.  It is also no longer imported by the requirements file.  Just remove this import.
> Remove cirq_google

- dev_tools/requirements/envs/dev.env.txt
- dev_tools/requirements/envs/pytest-extra.env.txt
- src/openfermion/resource_estimates/pbc/thc/factorizations/thc_jax.py
- src/openfermion/resource_estimates/thc/factorize_thc.py
- src/openfermion/resource_estimates/thc/utils/thc_factorization.py
- src/openfermion/resource_estimates/thc/utils/thc_objectives.py
Closes #893.
Also exposes the `penalty_param` for L2 regularization in the THC procedure to the top-level `thc_via_cp3` function.
> JAX config updates and expose `penalty_param`

- .github/workflows/ci.yml
- .github/workflows/nightly.yml
1) Update versions of actions like `checkout`
2) Define undefined variable `cirq-version` in ci.yml
3) Take advantage of pip cache offered by `setup-python`.
> Update CI worfklow actions & fix minor bug

- src/openfermion/transforms/repconversions/operator_tapering.py
Comparing using "is" instead of "==" would sometimes lead to incorrect results
> Fix comparison in freeze_orbitals

- .github/workflows/nightly.yml
More combinations of {OS, Python, architecture} are missing than I thought. This adjusts some requested versions to try to find a working combination for the matrix of combinations.
> Fix nightly ci workflow failures

- .github/workflows/nightly.yml
We don't need to hard-code the repository org/name combo.
> Use a variable to get the correct repo

- .github/workflows/nightly.yml
This is safer, and doesn't need a version either.
> Use local reference to workflow path

- .zenodo.json
Zenodo is an open repository maintained by CERN for preserving research data and software. It assigns permanent unique identifiers to each repository so it can be identified and cited. Zenodo also provides an integration mechanism allowing GitHub repository owners to arrange for GitHub releases to be sent automatically to Zenodo when they are made.
In order to provide users with (i) a way to override the values obtained via the GitHub API and (ii) to set other metadata fields available in Zenodo but not in GitHub, the Zenodo-GitHub integration mechanism will also look for a `.zenodo.json` file at the top level of a repository.
This PR adds a `.zenodo.json` file for OpenFermion; separately, we will turn on the GitHub-Zenodo integration for this repository, so that OpenFermion releases are …
> Add .zenodo.json file

- .zenodo.json
Looking at the publications again, I see Google listed first, so I changed it to match.
> Correct Nick Rubin's affiliation

- src/openfermion/linalg/linear_qubit_operator_test.py
- src/openfermion/linalg/sparse_tools_test.py
In SciPy 1.14, they removed the `.A` sparse matrix attribute; users are now supposed to call `.toarray()` instead.
> Replace no-longer-available SciPy constructs

- README.rst
- setup.py
This fixes a problem with a couple of links, some typos, adds a couple of badges, adds alt text to logo images, and tries to adjust some spacing issues. (Note that the result looks better on PyPI than on GitHub because of GitHub's poor support for reStructuredText.) There is very little actual content change in the README file here, apart from some changes in a few words here and there in an effort to improve clarity.
It also fixes a small bug in setup.py.
> Minor enhancements to README file & fix to setup.py

- dev_tools/packaging/produce-package.sh
- dev_tools/packaging/verify-published-package.sh
- dev_tools/requirements/deps/packaging.txt
This fixes a few small problems with the packaging scripts, replaces the deprecated `python3 -m setup.py bdist` command with the `build` equivalent, and slightly enhances and cleans up `produce-package.sh`.
> Update & enhance packaging scripts

- src/openfermion/_version.py
This updates `src/openfermion/_version.py` to record the version number 1.7.0 for the release.
> Version bump to 1.7.0

- .github/workflows/ci.yml
When a pull request is merged, it causes a push event on the main branch, which ends up causing this workflow to be executed twice when the merge occurs.
> Delete trigger on push events

- .github/workflows/ci.yml
- .github/workflows/nightly-pytest.yml
Google best practices for GitHub Actions recommend setting timeouts on jobs, to guard against unexpected problems causing jobs to take the full 60 minute GitHub default (go/github-actions#set-a-job-timeout).
> Add timeouts to jobs

- .github/workflows/ci.yml
This adds a step to check if Python files were actually changed before running tests. The setup is done in such a way that other file types besides Python can be added in the future.
> Improve efficiency by testing if any files changed

- .github/workflows/ci.yml
Looking for job names when configuring branch protection rules on the repo has become difficult because all jobs show up in the list of available checks, even if the jobs are not meant to be used directly.
> Change subjob names so they're recognizable

- .github/problem-matchers/README.md
- .github/problem-matchers/pylint.json
- .github/problem-matchers/yamllint.json
- .github/workflows/ci.yml
- .yamllint.yaml
Add another CI check for YAML files. They're used in Ci workflows,
config files, and in the docs/ directory.
> Add YAML file linter

- .github/workflows/ci.yml
- .github/workflows/nightly-pytest.yml
Per Google security guidance, action versions should be pinned to commit hashes and not simply using something like `@v4`.
> Pin action versions to commit hashes

- .github/workflows/ci.yml
- .github/workflows/nightly-pytest.yml
Google security best practices mandate the use of specific runner versions instead of "-latest".
> Use specific versions of GitHub runners

- .github/workflows/ci.yml
Once again, I'm hitting the problem that GitHub sometimes uses slightly different Python versions in parallel job invocations. It's not enough to use "3.12"; you have to give a full number like "3.12.8" to be sure that all jobs use the same version. Otherwise, since the version is part of the cache key, if different jobs get different python versions, they don't end up being able to use the same cache.
> Specify full x.y.z Python versions

- setup.py
This fixes issue https://github.com/quantumlib/OpenFermion/issues/887.  It removes the documentation source files from the installation.
Including the documentation `.md` and tutorial `.ipynb` files in the `pip` package installation seems unnecessary; the file end up in a very unusual location where users are unlikely to find them (which makes the value of their inclusion questionable), and the same content is available online (https://quantumai.google/openfermion).
> Remove doc source files from installation

- .github/workflows/ossf-scorecard.yaml
Let's reduce the frequency of this. We don't have enough untrusted contributors to warrant running this on every push.
> Only run Scorecard 1/day, not on every push

- .github/workflows/save-repo-stats.yaml
GitHub's repository statistics feature only keeps data for the last 14 days. The workflow at https://github.com/jgehrcke/github-repo-stats provides a way to daily data on a daily basis to overcome the 14 day limitation.
> Add workflow to persist GH repo stats > 14 days

- .zenodo.json
Somehow I missed the extra comma after the very last element in the JSON structure.
This is why there needs to be a JSON validator in the CI workflow.
> Remove extra comma at end of .zenodo.json file

- .github/problem-matchers/README.md
- .github/problem-matchers/hadolint.json
- .github/workflows/ci.yml
- .hadolint.yaml
This performs static checking on the (currently) two Dockerfiles in the OpenFermion repository for syntax validity and common best practices.
> Add Dockerfile linting to CI checks

- .github/dependabot.yaml
It's generating PRs due to version changes in transitive dependencies. It seems to make more sense to make it pay attention only to requirements/deps/, and not also requirements/envs/.
> Make Dependabot not look at requirements/env

- .github/problem-matchers/README.md
- .github/problem-matchers/shellcheck.json
- .github/workflows/ci.yml
- .shellcheckrc
This adds a job to the CI checks to run a shell script linter.
> Add shellcheck for shell script linting

- .github/workflows/ci.yaml
A fix I had in a testing version of this workflow didn't make it to the real GitHub repo for OpenFermion. The syntax passes YAML linting but is actually subtly incorrect and does not produce the expected behavior.
> Fix values of changed files variables

- .github/workflows/ci.yaml
- .github/workflows/osv-scanner.yaml
- README.rst
The sample workflows for the OSV scanner make it run on every PR, but
that doesn't make sense to me; better would be to run it only if a
requirements file is changed in a PR. So, that's what this does.
> Run OSV scan on PRs if requirements files are changed

- .github/workflows/osv-scanner.yaml
- .osv-scanner.toml
OSV prior to version 2.0 is unable to parse pip version specs correctly, as explained by one of the developers in the following comment from January 2025:
https://github.com/google/osv-scanner/issues/1483#issuecomment-2585999293
The suggested workaround is to configure osv-scanner to ignore the particular cases it complains about. The following are all about NumPy, because osv-scanner can't understand the version spec "numpy>=1.24,<2.0" and therefore raises errors about all versions of NumPy, including very old ones. Ignoring these specific dependencies is okay because we will never use the old versions of NumPy and it doesn't block detection of future new vulnerabilities.
> Ignore false positives from osv-scanner

- CONTRIBUTING.md
There is no substantive content change in this PR; it's just to fix some typos and while we're at it, update a couple of paragraphs to the newer version from the template repo.
> Fix a broken sentence, a misspelling, and update some text

- .github/workflows/osv-scanner.yaml
The documentation wasn't clear on this; it makes it scan .git/, which seems unnecessary for us.
> Don't use --include-git-root option with osv-scanner

- dev_tools/conf/pytest.ini
They're deprecation warnings that are harmless currently.
> Silence asyncio_default_fixture_loop_scope warnings

- .github/workflows/dependabot-pr-trimmer.yaml
Remove the command summary, because when using merge queues the
resulting commit messages are overly bloated.
> Add workflow to trim Dependabot PR message bodies

- .github/workflows/dependabot-pr-trimmer.yaml
The problem we're trying to solve is only an issue when Dependabot PRs are merged by the merge queue, so the trigger should reflect that.
In addition, the permissions can be tightened up a little bit.
> Dependabot trimmer only needs to run on merge queues

- .github/workflows/dependabot-pr-trimmer.yaml
The trimming needs to be performed before the PR is merged so that the commit message is based on the trimmed version. This prevents us from using events such as the PR getting closed or merged. Triggering on merge queue events is also problematic, because a merge_queue event doesn't have the equivalent of "pull_request.user" and we need that to test if the PR came from Dependabot. So instead, this workflow triggers when auto-merge is enabled for the PR.
> Trigger on auto_merge_enabled

- .github/ISSUE_TEMPLATE/1-bug-report.yml
- .github/ISSUE_TEMPLATE/2-feature-request.yml
- .github/ISSUE_TEMPLATE/config.yml
This adds some forms for new issues and feature requests. They are essentially identical to the forms recently [added in the qsim repository](https://github.com/quantumlib/qsim/tree/master/.github/ISSUE_TEMPLATE).
> Add issue templates using GitHub forms

- src/openfermion/resource_estimates/pbc/hamiltonian/cc_extensions.py
On line 72, the variable eri_kpt is assigned to itself. It's not clear what it should be instead – either something is missing on the RHS or else it's just a pointless assignment.
```python
if dtype == float:
eri_kpt = eri_kpt.real
eri_kpt = eri_kpt
```
Resolves issue #926.
> Fix #926: remove self-assignment

- src/openfermion/conftest.py
Some of the tests became more flaky with the move to NumPy 2. In all cases, random numbers were involved at some point. Setting a fixed random seed made the tests reproducible and (so far) seems to have stopped the flakiness.
> Set a fixed random seed during testing

- src/openfermion/resource_estimates/pbc/thc/factorizations/isdf.py
In lines 587-589, a variable is getting assigned to itself, which is probably an error:
```python
else:
delta_gs = [g_vectors] * num_kpts
g_mapping = g_mapping
```
Around lines 912-917, the same thing happens with another variable:
```python
elif kmeans_weighting_function == "sum_squares":
weighting_function = np.einsum(
"kRi,kRi->R", bloch_orbitals_mo.conj(), bloch_orbitals_mo, optimize=True
)
weighting_function = weighting_function
```
Resolves issue #924.
> Fix #924: remove self-assignments

- dev_tools/requirements/deps/oldest-versions.txt
- dev_tools/requirements/deps/runtime.txt
- dev_tools/requirements/envs/dev.env.txt
- dev_tools/requirements/envs/format.env.txt
- dev_tools/requirements/envs/mypy.env.txt
- dev_tools/requirements/envs/pip-tools.env.txt
- dev_tools/requirements/envs/pylint.env.txt
- dev_tools/requirements/envs/pytest-extra.env.txt
- dev_tools/requirements/envs/pytest.env.txt
- dev_tools/requirements/max_compat/dev.env.txt
- dev_tools/requirements/max_compat/pytest-max-compat.env.txt
This updates the minimum version of NumPy to 2, and cirq-core to 1.5 (the latter is needed to support NumPy 2).
> Partly fix #1008 and #1024: update dependencies and environment files for NumPy 2

- src/openfermion/chem/molecular_data.py
- src/openfermion/circuits/gates/common_gates_test.py
- src/openfermion/ops/operators/binary_code.py
- src/openfermion/ops/representations/interaction_operator.py
Update some files to use constructs compatible with NumPy 2.
A separate PR (#1055) updates the requirements files & dependencies for NumPy 2.
> Partly fix #1008 and #1024: adjust files to support NumPy 2

- src/openfermion/linalg/linear_qubit_operator.py
In Python 3.12, on Linux at least, `src/openfermion/testing/performance_benchmarks_test.py` produces the following warnings:
```
~/.pyenv/versions/3.12.5/lib/python3.12/multiprocessing/popen_fork.py:66: RuntimeWarning:
os.fork() was called. os.fork() is incompatible with multithreaded code, and JAX is
multithreaded, so this will likely lead to a deadlock.
self.pid = os.fork()
src/openfermion/testing/performance_benchmarks_test.py::test_run_linear_qop
src/openfermion/testing/performance_benchmarks_test.py::test_run_linear_qop
src/openfermion/testing/performance_benchmarks_test.py::test_run_linear_qop
src/openfermion/testing/performance_benchmarks_test.py::test_run_linear_qop
src/openfermion/testing/performance_benchmarks_test.py::test_run_linear_qop …
```
> Fix Python 3.12 deprecation warning about os.fork()

- src/openfermion/circuits/slater_determinants.py
- src/openfermion/circuits/slater_determinants_test.py
- src/openfermion/ops/representations/polynomial_tensor_test.py
- src/openfermion/ops/representations/quadratic_hamiltonian_test.py
Method `orbital_energies` in is deprecated in file `quadratic_determinants.py`; its replacement is method `diagonalizing_bogoliubov_transform`.
> Fix #1064: replace calls to deprecated method `orbital_energies`

- dev_tools/shell_tools.py
In Python 3.12, the code in `shell_tools.py` produces the following warnings when running `check/pytest`:
```
dev_tools/shell_tools_test.py::test_run_cmd_raise_on_fail
dev_tools/shell_tools.py:185:
DeprecationWarning: There is no current event loop
result = asyncio.get_event_loop().run_until_complete(
```
The fix involves managing the event loop. The updated functions now try to get the current running event loop; if no loop is running, they create a new one, use it, and then close it.
Note: commit [c3ab0fa](https://github.com/quantumlib/OpenFermion/pull/1071/commits/c3ab0fab591d02668647a5d9074b0118a9c4a19e) has the actual code changes. Commit [ba775f5](https://github.com/quantumlib/OpenFermion/pull/1071/commits/ba775f57d62870ed87edf5a48affcfbfbce82901) contains purely formatting changes …
> Fix warning about asyncio.get_event_loop() in Python 3.12

- .github/dependabot.yaml
Need to update the labels used, after recent changes to the GitHub labels.
> Update labels used by Dependabot

- src/openfermion/ops/representations/polynomial_tensor.py
- src/openfermion/ops/representations/quadratic_hamiltonian.py
- src/openfermion/transforms/opconversions/qubitoperator_to_paulisum.py
- This fixes two typos of "representation" caught by the CommonTypos tool
> Fix typos in two files

- check/pytest
The default version of `grep` on macOS (at least through macOS 15) does not take a `-P` argument, which causes `check/pytest` to fail due to the call to `grep -P` on line 432:
```shell
grep -Pv '^(.\[0m)?[\.FEsx]+(.\[36m)?\s+\[\s*\d+%\](.\[0m)?$'
```
The problem is that `-P` is for using Perl-compatible regular expressions (PCRE), which are not standard in the BSD version of grep that comes with macOS. Switching to grep's extended regex syntax using `-E` resolves the problem.
> Fix #1118: avoid using "-P" with grep

- .github/workflows/ci.yaml
If a script in `./check/` or `./dev_tools/` is changed, it may affect the results of running CI tests. To account for that, this PR expands the file change filter to detect any changes in those directories. In addition, this PR widens the files tested in `.github/workflows` to include any file changes.
The result is that any change in the dev_tools, scripts, or the CI workflows will trigger all the tests, not only the file-type-specific tests.
> Make CI  run on any changes to tools, check scripts, and all workflow files

- .hadolint.yaml
The `hadolint` warning DL3009 is only relevant when optimizing a docker container's size. It's not needed for security or other reasons. Not only is this rule annoying; following the rule can also increase docker image build times. The benefit does not seem to outweight the drawbacks, so I added it to the list of ignored rules.
Conversely, DL3047 (about the syntax of CMD statements) is probably better to keep, as a matter of modern practices surrounding Dockerfiles.
> Update hadolint configuration

- src/openfermion/ops/operators/symbolic_operator.py
- src/openfermion/ops/operators/symbolic_operator_test.py
CodeQL scan [report #566](https://github.com/quantumlib/OpenFermion/security/code-scanning/566) flagged a regex used on line 165 of
`src/openfermion/ops/operators/symbolic_operator.py` as being potential subject to a DoS attach. The warning is this:
```python
pattern = r'(.*?)\[(.*?)\]'  # regex for a term
for match in re.findall(pattern, long_string, flags=re.DOTALL):
```
```
This regular expression that depends on a user-provided value
may run slow on strings with many repetitions of 'a'.
This regular expression that depends on a user-provided value
may run slow on strings starting with '[' and with many repetitions of '[a'.
This regular expression that depends on a user-provided value
may run slow on strings with many repetitions of 'a'.
This regular expression that depends on a …
```
> Fix #1120: change unsafe regex in symbolic_operator.py

- check/shellcheck
Problem: In bash `read -r -d "" VAR` expects a NUL character to terminate
the input line.  If missing read returns a failure exit status and thus
quits the shellcheck script due to its errexit option.
Solution: Terminate read input with the NUL character.
> Avoid early exit in check/shellcheck due to spurious read failure
