README.rst
Should have caught this last time
=> fixing another readme link

MANIFEST.in, README.rst, src/openfermion/tests/_example_test.py
Forgot to remove contributing.md from manifest since it is now in README.
Relaxed timeouts in case of slow machines.
=> updated manifest

docker/Dockerfile, docker/README.md
Dockerfile builds openfermion-projectq, openfermion-psi4, openfermion-pyscf
=> Updated Dockerfile and README

README.rst, docker/README.md
small changes to make docker stuff more clear.
=> more cosmetic changes to readmes

README.rst, docs/intro.rst, src/openfermion/measurements/__init__.py, src/openfermion/measurements/_equality_constraint_projection.py
Fixes https://github.com/quantumlib/OpenFermion/issues/38
Also fixed two pep8 violations in the measurement module.
=> added pip upgrade instructions

README.rst
=> Improve install instructions

README.rst, docker/README.md
=> added name links

README.rst, docker/README.md
More changes to docker readme.
=> Yet more readme updates

docker/README.md
Removed all of the "step x" phrases
=> Docker readme update

README.rst, docker/README.md
@yudongcao I am going to go ahead and merge this but please take a look when you get a chance. I went through and followed the instructions and found that as originally written it was a bit confusing. Also, I do not think we should attempt to explain all the details of how to use docker. Those interested can certainly take a look at the docker docs to learn more about its basics.
If you feel like I am removing anything super crucial, please let me know.
=> significantly simplified docker installation instructions

docker/README.md
=> more docker docs update

src/openfermion/hamiltonians/_mean_field_dwave.py, src/openfermion/utils/__init__.py
Fixed a bug where I used floats where I should have used ints.
Also added an import statement.
=> Mean field sparse fix

README.rst, docker/README.md
* Added a link to the arXiv paper.
* Fixed the punctuation on a couple author names.
* Simplified docker installation instructions.
=> Paper link

README.rst
=> made OS requirements more clear

docs/conf.py, docs/openfermion.rst, src/openfermion/ops/_interaction_rdm.py, src/openfermion/ops/_polynomial_tensor.py, src/openfermion/utils/_operator_utils.py, src/openfermion/utils/_slater_determinants.py, src/openfermion/utils/_sparse_tools.py, src/openfermion/utils/_unitary_cc.py
* Fixes #84 
* Fixes some sphinx errors
=> fixed failing docs

src/openfermion/ops/_interaction_operator.py, src/openfermion/ops/_interaction_rdm.py, src/openfermion/ops/_polynomial_tensor.py, src/openfermion/ops/_polynomial_tensor_test.py, src/openfermion/ops/_quadratic_hamiltonian.py
Now `n_body_tensors[()]` is a complex number, the constant term.
=> Incorporate constant into n_body_tensors dictionary of PolynomialTensor

src/openfermion/ops/_quadratic_hamiltonian.py, src/openfermion/transforms/__init__.py, src/openfermion/transforms/_conversion.py, src/openfermion/transforms/_conversion_test.py
- Added routine to convert QuadraticHamiltonian to FermionOperator
- Updated `get_fermion_operator` to work for general PolynomialTensor
- Some bug fixes in QuadraticHamiltonian
=> Conversion routines for QuadraticHamiltonian

NOTICE, README.rst, src/openfermion/tests/_example_test.py
* Moved Kevin Sung from non-alphabetical to alphabetical in recognition of substantial contributions
* Changed timeout on certain tests to avoid broken builds due to Travis CI server slowdown.
=> Demo tests update

src/openfermion/utils/_slater_determinants.py
- Use real numbers in Givens rotations if possible (this avoids warnings about casting complex numbers)
- Changes to comments and description
=> Minor changes to Givens rotations

src/openfermion/ops/_interaction_operator.py, src/openfermion/ops/_polynomial_tensor.py, src/openfermion/ops/_quadratic_hamiltonian.py, src/openfermion/ops/_quadratic_hamiltonian_test.py, src/openfermion/utils/_slater_determinants.py, src/openfermion/utils/_slater_determinants_test.py
- Made `constant` a property of PolynomialTensor, with getter and setter
- Turned some methods of QuadraticHamiltonian into properties
=> Use property decorators in PolynomialTensor and subclasses

README.rst, src/openfermion/_version.py
Getting ready for OpenFermion v0.2
=> updated arXiv citation and version

cloud_library/H_rings_sto-3g_0.7414, cloud_library/README.md
Your first cloud test begins now @jarrodmcc 
My files will come as .zip
=> added more hydrogen rings

cloud_library/README.md
Thanks to @Spaceenter for setting up the website for us!
=> added web front end for molecule cloud download

src/openfermion/hamiltonians/_fermion_spin_operators.py
=> Minor string adjustment to docs in spin-gens

src/openfermion/hamiltonians/_jellium_test.py
I did not think about this in detail and just guessed that this is a bug by looking at the code. @idk3 or @babbush please verify. This would fix the problem discussed at #192 and make that PR mergeable.
=> Bug in Jellium test?

src/openfermion/hamiltonians/_jellium_test.py, src/openfermion/utils/_operator_utils.py
This is a response to the problem being discussed at #192 . I think it's a nicer fix than the dirty one.
=> add n_qubits option to eigenspectrum

README.rst, examples/binary_code_transforms_demo.ipynb, src/openfermion/_version.py
Do not merge until revision has been uploaded to arXiv.
=> updated arXiv reference

src/openfermion/hamiltonians/_hubbard.py, src/openfermion/hamiltonians/_mean_field_dwave.py, src/openfermion/hamiltonians/_molecular_data.py, src/openfermion/utils/_sparse_tools.py, src/openfermion/utils/_sparse_tools_test.py, src/openfermion/utils/_special_operators.py
=> remove spin indexing keyword arguments

examples/binary_code_transforms_demo.ipynb, src/openfermion/ops/__init__.py, src/openfermion/ops/_binary_code.py, src/openfermion/ops/_binary_code_test.py, src/openfermion/ops/_symbolic_binary.py, src/openfermion/ops/_symbolic_binary_test.py, src/openfermion/transforms/__init__.py, src/openfermion/transforms/_binary_code_transform.py, src/openfermion/transforms/_binary_codes.py, src/openfermion/transforms/_binary_codes_test.py
Resolves #248.
- Rename SymbolicBinary to BinaryPolynomial
- Rename `_code_transform_functions.py` to `_binary_codes.py`.
=> Rename SymbolicBinary and _code_transform_funtions.py

src/openfermion/ops/_fermion_operator_test.py, src/openfermion/utils/__init__.py, src/openfermion/utils/_special_operators.py, src/openfermion/utils/_special_operators_test.py
The git diff looks weird because I changed the ordering of the operators in the file. All I actually did was add `sx_operator` and `sy_operator` though.
I also moved the tests for the number operator to the proper file.
=> Add sx and sy operators

src/openfermion/ops/_polynomial_tensor.py
- Fixed an error in the documentation.
- Prevent KeyError from occurring when accessing the constant.
=> Minor fixes to PolynomialTensor

setup.py
Second attempt to address #289 .
=> use future open in setup.py

src/openfermion/ops/__init__.py, src/openfermion/ops/_binary_code.py, src/openfermion/ops/_binary_code_test.py, src/openfermion/ops/_fermion_operator.py, src/openfermion/ops/_fermion_operator_test.py, src/openfermion/ops/_symbolic_operator.py, src/openfermion/ops/_symbolic_operator_test.py, src/openfermion/transforms/__init__.py, src/openfermion/transforms/_binary_codes.py, src/openfermion/transforms/_binary_codes_test.py, src/openfermion/utils/__init__.py, src/openfermion/utils/_operator_utils.py, src/openfermion/utils/_operator_utils_test.py
Much less ambitious refactoring than requested at #271 . I decided I don't think I care enough to do the rest anyway so let's say this fixes #271.
@max-radin @conta877 just letting you know I moved some of your functions!
=> Move prune_unused_indices, freeze_orbitals, and linearize_decoder

src/openfermion/ops/_polynomial_tensor.py, src/openfermion/ops/_polynomial_tensor_test.py, src/openfermion/ops/_symbolic_operator_test.py, src/openfermion/utils/_testing_utils.py
=> Generalize equality and arithmetic operations for PolynomialTensor to allow differing keys

examples/performance_benchmarks.py
Performance benchmark for get_linear_qubit_operator(), from issue [#339](https://github.com/quantumlib/OpenFermion/issues/339)
=> Add performance benchmark for get_linear_qubit_operator().

requirements.txt
=> updated h5py requirements

src/openfermion/utils/__init__.py, src/openfermion/utils/_operator_utils.py, src/openfermion/utils/_operator_utils_test.py
This will be used for the low rank stuff. @kevinsung are my doc strings okay?
=> Function to normal order in chemistry convention

src/openfermion/utils/__init__.py, src/openfermion/utils/_low_rank.py, src/openfermion/utils/_low_rank_test.py
Adding final function that will go in OpenFermion core to help assist with low rank circuit simulation.
=> Low rank circuits

src/openfermion/utils/_low_rank.py
=> fixing zero constant error

src/openfermion/utils/_low_rank_test.py
Previously this was actually casting to reals (somehow I thought it was a good to silence the warnings) and thus didn't actually introduce complex elements. Whoops!
=> fixed poor test

README.rst
Pretty self-explanatory. We like both packages.
=> remove recommendation

src/openfermion/utils/__init__.py, src/openfermion/utils/_testing_utils.py, src/openfermion/utils/_testing_utils_test.py
I find myself writing these lines a lot in some demos I'm making so might as well make it a function.
=> Added Haar random function

src/openfermion/_version.py
Ready for PyPI release after merging.
=> version bump

src/openfermion/ops/_boson_operator.py, src/openfermion/ops/_boson_operator_test.py, src/openfermion/ops/_fermion_operator.py, src/openfermion/ops/_quad_operator.py, src/openfermion/ops/_quad_operator_test.py, src/openfermion/ops/_qubit_operator.py, src/openfermion/ops/_symbolic_operator.py, src/openfermion/ops/_symbolic_operator_test.py
=> Make SymbolicOperator abstract

src/openfermion/hamiltonians/_molecular_data.py, src/openfermion/hamiltonians/_molecular_data_test.py
This reduces boilerplate for situations in which you just want to get an InteractionOperator.
@jarrodmcc do you think the way of specifying the active space (number of electrons, number of active orbitals) is reasonable?
=> Wrapper function for loading a molecular Hamiltonian

src/openfermion/hamiltonians/__init__.py
Forgot to expose the function defined in #432
=> Expose load_molecular_hamiltonian

src/openfermion/ops/_symbolic_operator.py, src/openfermion/ops/_symbolic_operator_test.py
=> Omit terms with zero coefficient in SymbolicOperator __str__

docs/other_projects.md
the paper of @obriente (see recent PRs) to the papers list.
=> added Bayesian PEA paper to projects

src/openfermion/hamiltonians/_general_hubbard_test.py, src/openfermion/utils/_lattice.py, src/openfermion/utils/_lattice_test.py
=> added independent enumeration of horizontal and vertical edges

src/openfermion/utils/__init__.py, src/openfermion/utils/_wedge_product.py, src/openfermion/utils/_wedge_product_test.py
The two tensors are the moments for a particular sequence of
fermionic ladder operators.
Symmetric vs anitysmmetric could be an easy extension to this code.
=> Wedge product code between two tensors

src/openfermion/utils/_wedge_product.py
I don't know how this one slipped through ...
=> Remove import for Python 2 compatibility

examples/requirements.txt
Move requirements for notebooks into the examples subdirectory so that
they can be used by mybinder.org, but prevent them from being pulled
into dependency trees of upstream projects.
Resolves: https://github.com/quantumlib/OpenFermion/issues/551
Dependency tree before:
```
future 0.18.2 Clean single-source support for Python 3 and 2
h5py 2.10.0 Read and write HDF5 files from Python
├── numpy >=1.7
└── six *
jupyter 1.0.0 Jupyter metapackage. Install all the Jupyter components in one go.
├── ipykernel *
│   ├── appnope *
│   ├── ipython >=5.0.0
│   │   ├── appnope * (circular dependency aborted here)
│   │   ├── backcall *
│   │   ├── colorama *
│   │   ├── decorator *
│   │   ├── jedi >=0.10
│   │   │   └── parso >=0.5.2
│   │   ├── pexpect *
│   │   │   └── ptyprocess >=0.5
│   │   ├── …
```
=> Split out notebook requirements

examples/requirements.txt, requirements.txt, src/openfermion/ops/_binary_polynomial.py, src/openfermion/ops/_symbolic_operator.py, src/openfermion/utils/_channel_state.py, src/openfermion/utils/_lattice.py, src/openfermion/utils/_special_operators.py
=> Drop Python 2 compatibility library "six"

src/openfermion/_version.py
Version 0.11.0 has been released.
=> Bump version

src/openfermion/hamiltonians/_plane_wave_hamiltonian.py, src/openfermion/hamiltonians/_plane_wave_hamiltonian_test.py
Also, made numpy import explicit (symbols from numpy were previously implicitly picked up from _jellium module).
=> Wildcard import cleanup in plane wave Hamiltonian

README.rst
Added the github workflows badge along with removing the supported
versions badge.
=> New README badges

src/openfermion/__init__.py, src/openfermion/circuits/__init__.py, src/openfermion/circuits/primitives/__init__.py
Looks like this function was overlooked.
=> Expose prepare_gaussian_state

docs/projects.md
Removed OFC and reordered projects
=> Remove ofc from projects in docs

docs/overview.md
=> Found another OFC reference

src/openfermion/__init__.py, src/openfermion/measurements/__init__.py, src/openfermion/measurements/fermion_partitioning.py, src/openfermion/measurements/fermion_partitioning_test.py
New version of #554 as the old PR had some weird git history and needed to be updated. I've also responded to the comments from @kevinsung and @vtomole , thanks for the feedback!
=> Fermion partitioning

docs/_index.yaml
Includes content and styling updates.
=> Update docs landing page.

src/openfermion/linalg/wedge_product_test.py, src/openfermion/measurements/fermion_partitioning_test.py
We might want to consider testing incrementally
=> Slight increase in testing speed

src/openfermion/transforms/opconversions/binary_code_transform.py, src/openfermion/transforms/opconversions/binary_codes.py, src/openfermion/transforms/opconversions/bksf.py
=> Add type hint for binary tranform

src/openfermion/functionals/contextuality.py
I added type hints to function parameters and function returns.
=> Add type hints to functionals

src/openfermion/__init__.py, src/openfermion/hamiltonians/hartree_fock.py, src/openfermion/linalg/__init__.py, src/openfermion/linalg/rdm_reconstruction.py, src/openfermion/linalg/rdm_reconstruction_test.py
=> Valdemoro 3-RDM reconstruction

src/openfermion/ops/operators/symbolic_operator.py
PR implementing the change requested in #702
=> made _issmall() a static member of SymbolicOperator addressing #702

src/openfermion/__init__.py, src/openfermion/linalg/__init__.py, src/openfermion/linalg/rdm_reconstruction.py, src/openfermion/linalg/rdm_reconstruction_test.py
Correcting the spelling on C. Valdemoro's name.
Mea Culpa.
=> Name change on RDM reconstruction function.

src/openfermion/_version.py
Pypi latest says moving the patch index should be the latest
=> For pypi version recent

src/openfermion/utils/operator_utils.py, src/openfermion/utils/operator_utils_test.py
I've noticed that `count_qubits` in `operator_utils` doesn't handle `IsingOperator` and couldn't find a good reason why not, so I added it.
=> Added IsingOperator to count_qubits.

docs/_book.yaml, docs/fqe/tutorials/fermi_hubbard.ipynb
Adds a tutorial on how to simulate the Fermi-Hubbard model using FQE. Most of this tutorial was written by @ncrubin.
=> [FQE] Add Fermi-Hubbard tutorial

docs/fqe/tutorials/hamiltonian_time_evolution_and_expectation_estimation.ipynb
This fixes the colab, and will get the import build to stop failing.
=> Direct download the missing file

src/openfermion/_version.py
OpenFermion 1.3 is an incremental update with some fixes and improvements (see below). Crucially, we have moved from pinning to a specific version of Cirq to having a minimum supported version of Cirq (0.12 for this release).
- Implement Bravyi-Kitaev for InteractionOperator (#753)
- Fix unexpected behavior of symmetry_conserving_bravyi_kitaev (#734) 
- Revamp CI: matrix, multi-Cirq (#755)
=> Release v1.3.0

src/openfermion/_version.py
following the 1.3 release #758
=> Reset version to "dev"

src/openfermion/ops/representations/quadratic_hamiltonian.py, src/openfermion/ops/representations/quadratic_hamiltonian_test.py
=> Fix QuadraticHamiltonian diagonalization

docs/tutorials/circuits_2_diagonal_coulomb_trotter.ipynb
=> Update DropNegligible to cirq.drop_negligible_operations

docs/fqe/tutorials/fermi_hubbard.ipynb
- Docs are still failing due to taking exponentials of sparse matrices.
- Change them to dense to get docs working.
=> Change a few more sparse matrices to dense to get docs working

docs/fqe/tutorials/fermi_hubbard.ipynb
- Oops, I got too aggressive changing matrices to dense.
- These two were not sparse matrices.
=> Revert dense matrix

docker/README.md, docs/fqe/tutorials/diagonal_coulomb_evolution.ipynb, docs/fqe/tutorials/hamiltonian_time_evolution_and_expectation_estimation.ipynb, docs/tutorials/intro_to_openfermion.ipynb, src/openfermion/circuits/primitives/ffft.py, src/openfermion/contrib/representability/_namedtensor.py, src/openfermion/linalg/givens_rotations.py, src/openfermion/linalg/linear_qubit_operator.py, src/openfermion/ops/representations/doci_hamiltonian.py, src/openfermion/ops/representations/polynomial_tensor.py, src/openfermion/resource_estimates/README.md, src/openfermion/resource_estimates/thc/factorize_thc.py, src/openfermion/resource_estimates/thc/spacetime.py, src/openfermion/transforms/opconversions/term_reordering.py, src/openfermion/transforms/repconversions/qubit_operator_transforms.py, src/openfermion/transforms/repconversions/qubit_tapering_from_stabilizer.py, src/openfermion/transforms/repconversions/weyl_ordering.py
=> Apply suggestions from CommonTypos checker

dev_tools/conf/.pylintrc, pyproject.toml
=> Add black pyproject

src/openfermion/_version.py
It's been a while and I need a new release for qualtran PRs. Bumping to 1.6 as some new features were added including PBC resource estimates.
=> Bump version for release.

MANIFEST.in, setup.py
I was a bit too quick to bump the version it seems. The path was wrong for the resource estimates requirements. Also the manifest file was outdated.
=> Fix setup resource path

dev_tools/requirements/envs/dev.env.txt, dev_tools/requirements/envs/format.env.txt, dev_tools/requirements/envs/mypy.env.txt, dev_tools/requirements/envs/pip-tools.env.txt, dev_tools/requirements/envs/pylint.env.txt, dev_tools/requirements/envs/pytest-extra.env.txt, dev_tools/requirements/envs/pytest.env.txt, dev_tools/requirements/max_compat/dev.env.txt, dev_tools/requirements/max_compat/pytest-max-compat.env.txt, dev_tools/requirements/run-pip-compiles.py
Nothing more than running `re-pip-compile-in-docker.sh` (and including a spelling typo fix)
=> Bump requirements

docs/tutorials/intro_workshop_exercises.ipynb, docs/tutorials/jordan_wigner_and_bravyi_kitaev_transforms.ipynb
The old link doesn't work anymore.
=> Update the link to Nielsen's notes.

.github/SECURITY.md
=> Add security policy statement

CODE_OF_CONDUCT.md, SUPPORT.md
=> Add CoC and support.md files

.github/workflows/nightly-pytest.yml, .github/workflows/nightly.yml
Finding working combinations was a lot harder than expected. Modularizing into a reusable subworkflow helps avoid repeating the matrix definition.
=> Modularize workflow & find working os/arch/python combos

.github/workflows/ci.yml, .github/workflows/nightly.yml
Trying to use the result of the Pytest jobs for branch check conditions isn't working as expected. It seems necessary to add a result job, and test the outcome of that.
=> Split Pytest jobs into separate matrix & results steps

.github/workflows/ci.yml
Forgot to update the version here after the changes elsehwere.
=> Update version of python for max compat tests

.github/workflows/ossf-scorecard.yaml
Based on https://github.com/ossf/scorecard-action
=> Add workflow for Scorecard

.github/problem-matchers/jsonlint.json, .github/workflows/ci.yml, .jsonlintrc
This adds another CI check, this time for JSON validation & linting.
=> Add JSON lint check to ci.yml

.github/problem-matchers/README.md, .github/problem-matchers/black.json, .github/problem-matchers/mypy.json, .github/problem-matchers/pytest.json, .github/workflows/ci.yml, .github/workflows/nightly-pytest.yml
This adds a couple more problem matcher JSON files, for pytest and mypy.
=> Add problem matchers for mypy and pytest

README.rst
Fix the destination link and the workflow file name.
=> Update badge for CI workflow status

docs/tutorials/tutorial-requirements.txt
tutorial-requirements.txt used older versions of packages that had multiple security vulnerabilities and weren't in sync with what is in dev_tools/conf/deps/runtime.txt. This changes them to be the same.
=> Update tutorial-requirements.txt to match regular deps

README.rst
A hyphen here, a minor change of words there, an extra newline elsehwere.
=> Tiny edits to README

CITATION.cff
This adds more orienting comments in the file and tightens up the formatting to (hopefully) improve human readibility.
=> Add more comments & reformat slightly

CITATION.cff
This doesn't change the content except for correcting a couple of mixed-up URLs in the "identifiers" section.
=> Add comments, fix URLs, and reformat CITATION.cff

.editorconfig, .github/workflows/ci.yaml, .github/workflows/codeql.yaml, .github/workflows/nightly-pytest.yaml, .github/workflows/nightly.yaml, .github/workflows/osv-scanner.yaml, .github/workflows/scorecard.yaml, .gitignore, .hadolint.yaml, .markdownlintrc, .osv-scanner.toml, .shellcheckrc, .yamllint.yaml
Apparently I misread guidance somewhere, and license headers are not optional for these sorts of files after all.
=> Add missing license headers

README.rst
Seems to fail on PyPI, and anyway, it's not important.Seems to fail on PyPI, and anyway, it's not important.
=> Remove CI badge

check/pylint-changed-files
This is adapted from Cirq's script of the same name.
=> Add check/pylint-changed-files
